apiVersion: v1
kind: Service       
metadata:
  name: user-service-redis-db # Name of the Kubernetes resource
  labels:           
    app: user-service-redis-db
    role: master
    tier: backend
spec:
  ports:
  - port: 6379       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: 6379
  selector:          # Map any Pod with the specified labels to this service
    app: user-service-redis-db
    role: master
    tier: backend
