
apiVersion: v1
kind: Service
metadata:
 name: hazelcast-kubernetes-service
spec:
 type: ClusterIP
 selector:
   app: hazelcast-kubernetes-service
 clusterIP: None
 ports:
 - name: hz-port-name
   port: 5701
   protocol: TCP

